### ISSUE TITLE
Excuse me, this is SSR?

### ISSUE THREAD

**Issue by thearabbit** [chris-visser/meteor-vue-admin#14]
Excuse me, this is Vue+Meteor SSR?
Which one better `SSR Vs CSR`

**Comment by chris-visser** [comment]
For dashboard systems that don't have a public facing area I would say CSR. There are some use-cases though where you would want CSR on dashboard systems. For example to make older screenreaders work or to show initial loading states. 

In most cases SSR is mostly a SEO thing. That's why this dashboard is not SSR, but the other boilerplates are.

**Comment by thearabbit** [comment]
thanks for explain, but I am a bit understand.
